services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-history
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  history:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: history
    environment:
      - MONGOURL=${MONGOURL}
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - MONGOURL=${MONGOURL}
      - NODE_ENV=production
      - API_PREFIX=/api/v1
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "3001:3001"

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
