apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dragonfly-history
  name: dragonfly-history
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi