apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dragonfly-history
  name: dragonfly
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: dragonfly-history