apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dragonfly-history
  name: dragonfly-history
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dragonfly-history
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: dragonfly-history
    spec:
      containers:
        - image: ghcr.io/dragonflydb/dragonfly:latest
          name: dragonfly-history
          # args:
          #   - --maxmemory=4GiB
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data/dragonfly
              name: dragonfly-history
      restartPolicy: Always
      volumes:
        - name: dragonfly-history
          persistentVolumeClaim:
            claimName: dragonfly-history