apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: history-svc
  name: history-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 30005
  selector:
    io.kompose.service: history-svc
